// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/asset_one.proto

package proto_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*AssetOne_Dashboard
	//	*AssetOne_Table
	//	*AssetOne_Bucket
	Data isAssetOne_Data `protobuf_oneof:"data"`
}

func (x *AssetOne) Reset() {
	*x = AssetOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_asset_one_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOne) ProtoMessage() {}

func (x *AssetOne) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_one_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOne.ProtoReflect.Descriptor instead.
func (*AssetOne) Descriptor() ([]byte, []int) {
	return file_proto_asset_one_proto_rawDescGZIP(), []int{0}
}

func (m *AssetOne) GetData() isAssetOne_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *AssetOne) GetDashboard() *Dashboard {
	if x, ok := x.GetData().(*AssetOne_Dashboard); ok {
		return x.Dashboard
	}
	return nil
}

func (x *AssetOne) GetTable() *Table {
	if x, ok := x.GetData().(*AssetOne_Table); ok {
		return x.Table
	}
	return nil
}

func (x *AssetOne) GetBucket() *Bucket {
	if x, ok := x.GetData().(*AssetOne_Bucket); ok {
		return x.Bucket
	}
	return nil
}

type isAssetOne_Data interface {
	isAssetOne_Data()
}

type AssetOne_Dashboard struct {
	Dashboard *Dashboard `protobuf:"bytes,1,opt,name=dashboard,proto3,oneof"`
}

type AssetOne_Table struct {
	Table *Table `protobuf:"bytes,2,opt,name=table,proto3,oneof"`
}

type AssetOne_Bucket struct {
	Bucket *Bucket `protobuf:"bytes,3,opt,name=bucket,proto3,oneof"`
}

func (*AssetOne_Dashboard) isAssetOne_Data() {}

func (*AssetOne_Table) isAssetOne_Data() {}

func (*AssetOne_Bucket) isAssetOne_Data() {}

var File_proto_asset_one_proto protoreflect.FileDescriptor

var file_proto_asset_one_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6f, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x72, 0x61, 0x79, 0x66, 0x6c, 0x61,
	0x73, 0x68, 0x2e, 0x61, 0x6e, 0x79, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x01,
	0x0a, 0x08, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x64, 0x61,
	0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x67, 0x72, 0x61, 0x79, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x2e, 0x61, 0x6e, 0x79, 0x6f, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x09, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x35, 0x0a,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67,
	0x72, 0x61, 0x79, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x2e, 0x61, 0x6e, 0x79, 0x6f, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x05, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x66, 0x6c, 0x61, 0x73, 0x68,
	0x2e, 0x61, 0x6e, 0x79, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x06,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x35, 0x0a, 0x08, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x42, 0x08, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x72, 0x61, 0x79, 0x46, 0x6c, 0x61,
	0x73, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_asset_one_proto_rawDescOnce sync.Once
	file_proto_asset_one_proto_rawDescData = file_proto_asset_one_proto_rawDesc
)

func file_proto_asset_one_proto_rawDescGZIP() []byte {
	file_proto_asset_one_proto_rawDescOnce.Do(func() {
		file_proto_asset_one_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_asset_one_proto_rawDescData)
	})
	return file_proto_asset_one_proto_rawDescData
}

var file_proto_asset_one_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_asset_one_proto_goTypes = []interface{}{
	(*AssetOne)(nil),  // 0: grayflash.anyone.proto.AssetOne
	(*Dashboard)(nil), // 1: grayflash.anyone.proto.Dashboard
	(*Table)(nil),     // 2: grayflash.anyone.proto.Table
	(*Bucket)(nil),    // 3: grayflash.anyone.proto.Bucket
}
var file_proto_asset_one_proto_depIdxs = []int32{
	1, // 0: grayflash.anyone.proto.AssetOne.dashboard:type_name -> grayflash.anyone.proto.Dashboard
	2, // 1: grayflash.anyone.proto.AssetOne.table:type_name -> grayflash.anyone.proto.Table
	3, // 2: grayflash.anyone.proto.AssetOne.bucket:type_name -> grayflash.anyone.proto.Bucket
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_asset_one_proto_init() }
func file_proto_asset_one_proto_init() {
	if File_proto_asset_one_proto != nil {
		return
	}
	file_proto_dashboard_proto_init()
	file_proto_table_proto_init()
	file_proto_bucket_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_asset_one_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_asset_one_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AssetOne_Dashboard)(nil),
		(*AssetOne_Table)(nil),
		(*AssetOne_Bucket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_asset_one_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_asset_one_proto_goTypes,
		DependencyIndexes: file_proto_asset_one_proto_depIdxs,
		MessageInfos:      file_proto_asset_one_proto_msgTypes,
	}.Build()
	File_proto_asset_one_proto = out.File
	file_proto_asset_one_proto_rawDesc = nil
	file_proto_asset_one_proto_goTypes = nil
	file_proto_asset_one_proto_depIdxs = nil
}
